smooch/smooch-core-js

package.json
src/api/appUsers.js
src/api/base.js
src/api/conversations.js
src/api/webhooks.js
src/smooch-node.js
src/smooch.js
src/utils/auth.js
tests/specs/api/appUsers.spec.js
tests/specs/api/base.spec.js
tests/specs/api/conversations.spec.js
tests/specs/api/webhooks.spec.js
tests/specs/utils/auth.spec.js
tests/specs/wrappers/browser.spec.js
tests/specs/wrappers/node.spec.js

This simplifies the auth handling and fixes #8 .
@alavers

Moved auth information at the instance level

---

src/api/appUsers.js
src/api/base.js
tests/specs/api/appUsers.spec.js

@alavers I wasn't really sure how to make this only available to node, but I figure it doesn't really matter as long as it only accepts the jwt authenticate.

AppUsers create

---

package.json

Make babel-runtime a prod dependency

---

src/api/conversations.js
tests/specs/api/conversations.spec.js

Add endpoint to reset unread count

---

package.json

I'll publish 1.0.0 after merge

Update package.json after repo move

---

src/api/appUsers.js
tests/specs/api/appUsers.spec.js

This adds support for the push token api. It's needed by the web widget for Chrome notifications.
@alavers @mspensieri

Push Token endpoint

---

src/api/appUsers.js
tests/specs/api/appUsers.spec.js

@lemieux 
@mspensieri 
@alavers 
@dannytranlx 
@Mario54

Add update device API

---

src/api/appUsers.js
src/api/appUsersLink.js
tests/specs/api/appUsers.spec.js
tests/specs/api/appUsersLink.spec.js

@jugarrit @lemieux @dannytranlx @mspensieri 
This adds the endpoints for
`POST /appUsers/:userId/channels`
`DELETE /appUsers/:userId/channels/:channel`

Add linking API endpoints

---

src/api/appUsersLink.js
tests/specs/api/appUsersLink.spec.js

Rename deleteChannel to unlinkChannel

---

src/api/appUsers.js
tests/specs/api/appUsers.spec.js

@alavers @jugarrit @mspensieri @lemieux

Change ping API endpoint to a POST

---

README.md
src/api/menu.js
src/smooch-node.js
tests/specs/api/menu.spec.js

@jugarrit @dannytranlx @chloepouprom 
wrapping menu endpoints https://github.com/smooch/smooch/pull/1829

Wrap menu api

---

README.md
src/api/appUsers.js
src/api/conversations.js
tests/specs/api/appUsers.spec.js
tests/specs/api/conversations.spec.js

New endpoints for sending messages and uploading images.
`POST /appUsers/:appUser/messages`
`POST /appUsers/:appUser/images`
@dannytranlx @mspensieri @jugarrit

Add endpoints for sending message and uploading image

---

src/api/webhooks.js
tests/specs/api/webhooks.spec.js

Release 2.0.1

---

src/api/appUsers.js
src/api/appUsersViber.js
tests/specs/api/appUsersViber.spec.js

@lemieux @hebime @mspensieri @jugarrit

Add Viber QR code endpoint

---

.gitignore
package.json

Add minami jsdoc template

---

src/api/appKeys.js
src/api/apps.js
src/api/integrations.js
src/smooch-node.js
test/specs/api/appKeys.spec.js
test/specs/api/apps.spec.js
test/specs/wrappers/node.spec.js

The refactoring is now paying off.

Define wrappers for /v1/apps APIs

---

README.md
src/api/appUsers.js
test/specs/api/appUsers.spec.js

* wrap typing indicator api
* update readme too
* updated unit test
* fix unit tests
* fix unit tests

Typing indicator API (#65)

---

src/api/integrations.js
test/specs/api/integrations.spec.js

Also adds support for parameter type validation.

Add support for apn and fcm to integrations wrapper

---

README.md

Updating this table should be part of all future additions to smooch-core.

Add methods to table

---

README.md
src/api/appKeys.js
src/api/apps.js
src/api/integrationMenu.js
src/api/integrations.js
test/specs/api/integrationMenu.spec.js

Also fixed some typos and wrong endpoints in README

Add wrapper for integration menu

---

README.md
src/api/appKeys.js
src/api/apps.js
src/api/integrationMenu.js
src/api/integrations.js
test/specs/api/integrationMenu.spec.js

Add wrapper for integration menu (#78)

Release 3.4.1

---

package.json
src/api/apps.js
test/specs/api/apps.spec.js

This adds support for the new `Update App` API and for the new `settings` parameter in `Create App`

Add PUT app API

---

README.md
src/api/appUsers.js
test/specs/api/appUsers.spec.js

updated the readme with `/businesssystems` and `/channels` as well

Add new method for business systems API endpoint

---

src/api/appUsers.js
test/specs/api/appUsers.spec.js

* Add `conversationActivity`
* Mark `typingActivity` as deprecated

Add `conversationActivity`

---

src/api/integrations.js

hotfix to add messagebird to the integrations for smooch-core

Add messagebird to integrations

---

README.md

Update the `README` file to be more informative and clear with regards to the module methods.
_Partial screenshot_

Update the module methods table in README

---

.eslintrc
README.md
src/api/attachments.js
test/specs/api/attachments.spec.js

 Add attachments.delete

---

README.md
src/api/appUsers.js
test/specs/api/appUsers.spec.js

Implementation for new endpoint.

Add appUsers.delete

---

src/api/attachments.js
test/specs/api/attachments.spec.js

Add `for`, `userId`, `appUserId` attachments support
